export { default as AdminLogin} from '../components/adminLogin/AdminLogin';
export { default as NoticeView } from '../components/notice/NoticeView';
export { default as NoticeWrite } from '../components/notice/NoticeWrite';
export { default as DetailNotice } from '../components/notice/DetailNotice/DetailNotice';
export { default as Question } from '../components/question/Question';
export { default as ApproveList } from '../components/reportApprove/ApproveList';
export { default as ViewReport } from '../components/reports/ViewReport';
export { default as DetailApprove } from '../components/reportApprove/DetailApprove/DetailApprove';
export { default as DetailReport } from '../components/reports/DetailReport/DetailReport';
export { default as ModifyNotice } from '../components/notice/DetailNotice/ModifyNotice';